server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: none
        secure: true

pax:
  base-url: https://api.whatspos.com/p-market-api
  key: L936R3E0MXC7PE18QP9Y
  secret: 42BGUAXOEGVIIHH1H47BLT8A48P1BX7HPCGE4E90

goinsight:
  time-zone: Africa/Abidjan
  date-format: yyyy-MM-dd
  date-time-format: yyyy-MM-dd'T'HH:mm:ss'Z'
  full-history: true   # true pour 1ère exécution
  debug-columns: true
  greenpay:
    insight-id: 4e5fryeq        # ⚠️ à ajuster
    battery-insight-id: zr6unnm5 # ⚠️ à ajuster
    page-size: 1000
    max-pages: 15
    ingestion:
      enabled: true
      cron1: "0 0,30 12 * * *"
      cron2: "0 0 13 * * *"
      cron3: "0 0 14,15 * * *"
      cron4: "0 0 17-19 * * *"
      cron5: "0 30 19 * * *"

spring:
  datasource:
    url: jdbc:mysql://mysql-devgp.alwaysdata.net:3306/devgp_paxws?useSSL=false&allowPublicKeyRetrieval=true&tcpKeepAlive=true&connectTimeout=10000&socketTimeout=1200000&useUnicode=true&characterEncoding=utf8&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useServerPrepStmts=true&rewriteBatchedStatements=true
    username: devgp_paxapp
    password: PasswordPx2024
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariPool-1
      maximum-pool-size: 10
      minimum-idle: 2

      # Toujours < wait_timeout MySQL (900s chez toi) mais > durée d'un lot
      maxLifetime: 600000    # 10 min
      idleTimeout: 180000    # 3 min
      keepaliveTime: 120000  # 2 min

      validationTimeout: 5000
      connectionTimeout: 10000
  
  task:
    scheduling:
      pool:
        size: 4
      thread-name-prefix: Sched-

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.globally_quoted_identifiers: true
      hibernate.jdbc.batch_size: 300
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.batch_versioned_data: true
      hibernate.connection.provider_disables_autocommit: false
    open-in-view: false

auth:
  jwt:
    secret: mySecretKey123456789012345678902
    ttlMillis: 86400000
  enabled: true

app:
  cors:
    allowed-origins:
      - http://localhost:5173
      - http://127.0.0.1:5173

logging:
  level:
    root: INFO
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    com.example.paxapi: DEBUG
    org.springframework.scheduling: DEBUG
